Добавили CodeStyle
caof19/yandex.game pull request #1
Opened 2024-09-20 21:57 UTC by AlexandrovPavel

### Какую задачу решаем
_Создать репозиторий_ https://tracker.yandex.ru/YANDEXGAME-2

### Изменения

- обновил зависимости
   - добавил eslint-config-prettier, eslint-plugin-prettier
   - перенес из deps в devDeps prettier и обновил до актуальной версии
- изменил правила в config-файлах .prettierrc, .eslintrc и .editorconfig

2024-09-21 06:07 UTC, shuraleva requested changes

2024-09-21 06:07 UTC, shuraleva commented on packages/client/package.json
> +    "devDependencies": {
предлагаю сразу закинуть antd и типы для него, чтобы все могли начать делать формочки

2024-09-21 06:07 UTC, shuraleva commented on packages/client/package.json
> +        "typescript": "^4.8.2",
может посовременнее версию возьмем? В шаблоне как будто старовата)

2024-09-21 17:43 UTC, AlexandrovPavel commented on packages/client/package.json
> +    "devDependencies": {
Закинул в следующих PR

2024-09-21 17:49 UTC, AlexandrovPavel commented on packages/client/package.json
> +        "typescript": "^4.8.2",
Смотря что обновлять. Обновление может все сломать

2024-09-21 18:35 UTC, shuraleva approved these changes

2024-09-22 17:42 UTC, caof19 approved these changes
Единственное, добавь плз .nvmrc файл, и пропиши там версию v18.18.0, 16 не всегда стабильная, ниже юзать тем более не вижу смысла

2024-09-22 18:53 UTC, merged