YANDEXGAME-9: Вёрстка страницы форума
caof19/yandex.game pull request #12
Opened 2024-09-29 22:17 UTC by sCoruja

### Какую задачу решаем
1. Сделать роут для страницы форума

2. Сверстать экраны форума:

- экран создания топика

    • экран со всем топиками,

- экран одного топика с комментами,

    • функциональность добавления комментария к топику.

### Скриншоты/видяшка (если есть)
![изображение](https://github.com/user-attachments/assets/33f28037-9ec7-4cf3-ba66-5d786d11f9c9)
![изображение](https://github.com/user-attachments/assets/f63af90e-252c-4088-bb4a-13cd5d2d7819)
![изображение](https://github.com/user-attachments/assets/2f093219-9173-432e-8a46-debc2fc93795)

### TBD (если есть)

2024-09-30 18:06 UTC, caof19 requested changes

2024-09-30 18:06 UTC, caof19 commented on packages/client/src/pages/Forum/index.tsx
> +        setAuthorized(Math.random() > 0.5);
Это убрать, форум у нас стоит под проверкой авторизации в родительском компоненте  в файле packages/client/src/pages/index.tsx

2024-09-30 18:06 UTC, caof19 commented on packages/client/src/pages/Topic/index.tsx
> +        setAuthorized(Math.random() > 0.5);
Тоже убрать

2024-09-30 18:06 UTC, caof19 commented on packages/client/src/pages/index.tsx
> +            <Route path={routes.topic.path} component={Topic} />
А тут посмотреть по аналогии, тоже поместить как дочерний компонент в проверку авторизации, ниже пример есть

2024-09-30 20:38 UTC, sCoruja commented on packages/client/src/pages/index.tsx
> +            <Route path={routes.topic.path} component={Topic} />
\+

2024-09-30 20:38 UTC, sCoruja commented on packages/client/src/pages/Topic/index.tsx
> +        setAuthorized(Math.random() > 0.5);
\+

2024-09-30 20:39 UTC, sCoruja commented on packages/client/src/pages/Forum/index.tsx
> +        setAuthorized(Math.random() > 0.5);
\+

2024-09-30 20:52 UTC, sCoruja commented on packages/client/src/pages/index.tsx
> +            <Route path={routes.topic.path} component={Topic} />
\+

2024-10-01 06:18 UTC, kyzinatra commented
К сожалению не смогу проверить вашу работу, так как нет ни 1 апрува от ваших коллег. Попросите ваших коллег поставить апрув и отправляйте работу снова.

2024-10-01 10:02 UTC, caof19 approved these changes

2024-10-01 15:50 UTC, ex1one commented on packages/client/src/Components/CommentForm/index.tsx
> +export const CommentForm: React.FC<TCommentFormProps> = (props) => {
Сейчас мало пропсов приходит и вряд-ли в будущем будет много. Я бы props переписал бы на {onSubmit}, чтобы постоянно не обращаться к props.onSubmit.

2024-10-01 15:53 UTC, ex1one commented on packages/client/src/Components/CommentForm/index.tsx
> +    const changeHandler = (e: ChangeEvent) => {
ChangeEvent должен быть дженериком. Можно переписать на ChangeEvent<HTMLInputElement>, чтобы ниже не надо было писать "as"

2024-10-01 16:27 UTC, ex1one commented on packages/client/src/Components/CommentForm/index.tsx
> +        <Form autoComplete="off" onFinish={submitHandler.bind(this)}>
onFinish={submitHandler.bind(this)}

this будет undefined. Нужно переписать.

2024-10-01 16:27 UTC, ex1one commented on packages/client/src/Components/Topics/index.tsx
> +const Topic: React.FC<TTopicProps> = (props) => {
Избавится от FC, выше пояснил. Можно также деструктуризацию сделать пропсов

2024-10-01 16:28 UTC, ex1one commented on packages/client/src/pages/Forum/index.tsx
> +    const [topics, setTopics] = useState<TTopic[] | undefined>();
Если и делаешь такую логику, то выноси ее в отдельный компонент, где будет отображаться loader пока данные грузятся.

2024-10-01 16:29 UTC, ex1one commented on packages/client/src/pages/Topic/index.tsx
> +                            {comments && <Comments comments={comments} />}
Аналогично комментарию выше

2024-10-02 09:26 UTC, sCoruja commented on packages/client/src/pages/Topic/index.tsx
> +                                onSubmit={addCommentHandler.bind(this)}
\+

2024-10-02 09:26 UTC, sCoruja commented on packages/client/src/pages/Topic/index.tsx
> +                            {comments && <Comments comments={comments} />}
\+

2024-10-02 09:26 UTC, sCoruja commented on packages/client/src/pages/Forum/index.tsx
> +    const [topics, setTopics] = useState<TTopic[] | undefined>();
\+

2024-10-02 09:27 UTC, sCoruja commented on packages/client/src/Components/Topics/index.tsx
> +const Topic: React.FC<TTopicProps> = (props) => {
\+

2024-10-02 09:27 UTC, sCoruja commented on packages/client/src/Components/CommentForm/index.tsx
> +                        onChange={changeHandler.bind(this)}
\+

2024-10-02 09:27 UTC, sCoruja commented on packages/client/src/Components/CommentForm/index.tsx
> +        <Form autoComplete="off" onFinish={submitHandler.bind(this)}>
\+

2024-10-02 09:27 UTC, sCoruja commented on packages/client/src/Components/CommentForm/index.tsx
> +export const CommentForm: React.FC<TCommentFormProps> = (props) => {
\+

2024-10-05 07:44 UTC, ex1one commented
Нужно конфликты решить

2024-10-05 07:45 UTC, ex1one approved these changes

2024-10-05 08:33 UTC, merged