Добавил Error Boundary
caof19/yandex.game pull request #16
Opened 2024-10-03 18:39 UTC by ex1one

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-05 08:34 UTC, sCoruja approved these changes

2024-10-06 05:23 UTC, shuraleva requested changes

2024-10-06 05:23 UTC, shuraleva commented on packages/client/src/components/RootErrorBoundary/components/ErrorBoundaryFallback.tsx
> +        } else {
тут как будто не нужен этот else, потому что ифы закроются и в общем ретурне у тебя тоже самое написано

2024-10-06 05:23 UTC, shuraleva commented on packages/client/src/components/RootErrorBoundary/components/ErrorBoundaryFallback.tsx
> +            title="Простите, что-то пошло не так..."
предлагаю и title и subTitle вынести в константы над компонентом.
Оставить только этот ретурн и добавить одну функцию, которая будет определять статус, потому что все остальное одинаковое :)

а определение статуса тоже можно сократить (вроде такой вариант покрывает все ифы)
```
const getStatus = (status?: number) => [403, 404].includes(status) ? status.ToString() : "500";
const title ...
const subTitle ...
<ErrorBoundaryFallback ....

    const status = (error instanceof AxiosError && (error.response || error.request)) 
        ? getStatus(error.response?.status) 
        : "error";
 
     return <Result status title={title} subTitle={subTitle} {...other}>
            {children}
    </Result>>

2024-10-07 15:18 UTC, ex1one commented on packages/client/src/components/RootErrorBoundary/components/ErrorBoundaryFallback.tsx
> +        } else {
Тут не совсем одно и тоже. Я когда зашел в блок if, то у меня ошибка получается AxiosError. Из-за этого if я конечно могу спустится в нижний блок кода, но уже код становится запутанее. Это раз момент.

2 момент - такой код я сократил, чтобы в будущем его можно было отрефакторить. Пока просто мне не совсем понятно, какие ошибки у нас могут быть, как мы их будем обрабатывать.

Сделал, так чтобы много не думать :D

2024-10-08 15:46 UTC, shuraleva approved these changes

2024-10-09 16:56 UTC, merged