Установка пакетов и базовая настройка окружения
caof19/yandex.game pull request #2
Opened 2024-09-21 09:22 UTC by AlexandrovPavel

### Установка пакетов и базовая настройка окружения

### Установлены:
- axios
- react-route-dom
- history
- antd

2024-09-21 19:36 UTC, shuraleva requested changes

2024-09-21 19:36 UTC, shuraleva commented on packages/client/package.json
> +        "prettier": "^2.7.1",
тут по аналогии с соседним пром - многое надо увезти в дев

2024-09-22 19:45 UTC, AlexandrovPavel commented on packages/client/package.json
> +        "prettier": "^2.7.1",
Исправил в следующем PR (PR-3).

2024-09-23 10:26 UTC, shuraleva approved these changes

2024-09-23 10:35 UTC, merged