YANDEXGAME-25: Добавить Redux-хранилище.
caof19/yandex.game pull request #23
Opened 2024-10-08 20:43 UTC by AlexandrovPavel

### Какую задачу решаем
Добавить Redux-хранилище:
- данные хранятся и обрабатываются через Redux;
- состояния приложения хранятся в сторе;
- добавить в проект redux-toolkit;
- добавить слайс для регистрации;
- после авторизации класть информацию о юзере в слайс;

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-09 18:29 UTC, caof19 requested changes
Нужно переключать состояние после авторизации

2024-10-11 18:26 UTC, shuraleva approved these changes

2024-10-12 07:24 UTC, kyzinatra commented on packages/client/src/store/slice/auth/index.ts
> +            console.log("Logined ", state.isLogged);
Логи стоит удалить. В reducers их не стоит выводить. Есть devtools

2024-10-12 07:24 UTC, kyzinatra approved these changes
Отличная работа! Хорошее подключение redux. Не забывайте и дальше развивать его и использовать в своем коде

2024-10-13 18:04 UTC, merged