YANDEXGAME-30: Добавить API для лидерборда
caof19/yandex.game pull request #36
Opened 2024-10-25 15:25 UTC by sCoruja

### Какую задачу решаем
Подключено api лидерборда, рекорд пользователя записывается в таблицу по окончанию игры, так же юзер может посмотреть таблицу лидеров

### Скриншоты/видяшка (если есть)
![изображение](https://github.com/user-attachments/assets/2bec3ef3-927a-4aea-a934-7f71f7643c4e)

### TBD (если есть)

2024-10-29 18:48 UTC, shuraleva requested changes

2024-10-29 18:48 UTC, shuraleva commented on packages/client/src/pages/Game/filler.tsx
> +            onEndingGame();
мы, вроде, хотели считать победы пользователей. потому что просто кол-во очков все равно не может быть больше половины поля

2024-10-29 18:50 UTC, sCoruja commented on packages/client/src/pages/Game/filler.tsx
> +            onEndingGame();
а, забыл. исправлю

2024-10-30 04:52 UTC, sCoruja commented on packages/client/src/components/Layout/index.tsx
> +                            {isAuthenticated ? (
а как этим HOC менять ссылки в шапке в зависимости от авторизации?

2024-11-01 12:53 UTC, sCoruja commented on packages/client/src/pages/Game/filler.tsx
> +            onEndingGame();
\+

2024-11-01 20:19 UTC, caof19 approved these changes
Единственно только, добавь тогда плз в хедер и кнопку выхода

2024-11-02 18:45 UTC, shuraleva approved these changes

2024-11-03 07:23 UTC, kyzinatra commented on packages/client/src/service/hook/index.ts
> +    return login;
можно просто `return useAppSelector((state) => state.auth.user?.login);`

2024-11-03 07:24 UTC, kyzinatra approved these changes
Отличная работа по подключению api для лидерборда. Вопросов к этой части нет, все сделано отлично!

2024-11-11 19:17 UTC, merged