Yandexgame29.add o auth yandex
caof19/yandex.game pull request #37
Opened 2024-11-01 21:02 UTC by caof19

### Какую задачу решаем
Добавление OAuth от яндекс
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-11-02 19:46 UTC, shuraleva requested changes

2024-11-02 19:46 UTC, shuraleva commented on packages/client/src/pages/SignIn/index.tsx
> +            "/oauth/yandex/service-id?redirect_uri=http://localhost:3000/login",
хост наверное и должен браться из хоста, а не захардкожен быть)

2024-11-02 19:46 UTC, shuraleva commented on packages/client/src/service/const.ts
> +export const REDIRECT_URI = "http://localhost:3000/login";
и тут

2024-11-02 19:46 UTC, shuraleva commented on packages/client/src/utils/query.ts
> +export function setNewGet(key, value) {
это кажется нигде не используется

2024-11-02 19:46 UTC, shuraleva commented on packages/client/src/utils/query.ts
> +export function getQueryParam(key) {
попробуй вместо этого хук useSearchParams

2024-11-02 19:46 UTC, shuraleva commented on packages/client/src/utils/query.ts
> +export function removeQueryParam(param) {
изменить тоже можно через useSearchParams

2024-11-02 22:53 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +            "/oauth/yandex/service-id?redirect_uri=http://localhost:3000/login",
Тут согласен, нужно из констант брать

2024-11-02 22:54 UTC, caof19 commented on packages/client/src/service/const.ts
> +export const REDIRECT_URI = "http://localhost:3000/login";
Тут не понял что? Это файл с константами, в которых хранится константа

2024-11-03 07:35 UTC, shuraleva commented on packages/client/src/service/const.ts
> +export const REDIRECT_URI = "http://localhost:3000/login";
Я к тому, что значение не должно быть захардкожено, а браться из хоста приложения - переменной окружения или в нужном месте просто из хоста в браузере, потому что я например запускаю приложение на 5000+ порте, особенность мака. А завтра мы его задеплоим. И каждый раз менять в нескольких местах?

2024-11-03 12:01 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +            "/oauth/yandex/service-id?redirect_uri=http://localhost:3000/login",
Теперь константа

2024-11-03 12:01 UTC, caof19 commented on packages/client/src/service/const.ts
> +export const REDIRECT_URI = "http://localhost:3000/login";
Исправил

2024-11-03 12:02 UTC, caof19 commented on packages/client/src/utils/query.ts
> +export function setNewGet(key, value) {
Убрал, хотя если честно не совсем понял зачем. Если это сейчас не используется мной, то потом использовался бы кем то

2024-11-03 12:04 UTC, caof19 commented on packages/client/src/utils/query.ts
> +export function getQueryParam(key) {
Он работает только на 6+ версии, у нас 5,3

Не вижу смысла ради одного хука менять мажорную версию

2024-11-03 12:04 UTC, caof19 commented on packages/client/src/utils/query.ts
> +export function removeQueryParam(param) {
Убрал, не используется

2024-11-03 16:20 UTC, shuraleva approved these changes

2024-11-03 19:04 UTC, kyzinatra commented on packages/client/src/pages/SignIn/SignIn.module.css
> +    color: #ffffff;
Цвета лучше вынести в константы

2024-11-03 19:05 UTC, kyzinatra approved these changes
Хорошая реализация OAuth на клиенте. Понравилось, что вы обрабатываете ошибки. Вопросов к этой части нет, все сделано хорошо.

2024-11-09 11:15 UTC, sCoruja approved these changes

2024-11-10 09:52 UTC, ex1one approved these changes

2024-11-11 17:55 UTC, merged