Feature/8.sign in api
caof19/yandex.game pull request #7
Opened 2024-09-24 21:15 UTC by caof19

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-09-25 14:19 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +import "./style.css";
Лучше использовать модульные стили. Чтобы избежать конфликтов имен.

2024-09-25 14:23 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +const userFields = [
Я считаю, что можно не использовать доп.переменную для определения полей. А сразу хранить это в jsx. Как бы получается ты удалишь этот массив и просто создашь 2 Input компонента с такими props. Посмотри в моем pr реализацию - https://github.com/caof19/yandex.game/pull/4

По идее на странице регистрации не должно быть много inputs, чтобы так было необходимо сделать, чтобы избежать дублирования кода.

2024-09-25 14:30 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +        validate: [
Мне кажется, ты усложняешь код. Посмотри как у меня сделана в моем pr https://github.com/caof19/yandex.game/pull/4. Я просто добавил в rules: [{required: true, message: "Это поле обязательно"}], также вторым элементом второе правило.

2024-09-25 14:32 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +    const handleBlur = (fieldName: string, value: string, validateRule) => {
Это нужно убрать. Написал свой validator можно сказать) Ant Design предоставляет API для таких случаев. Код станет намного чище, понятнее и проще.

2024-09-25 14:33 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +                        style: {
Если и добавлять свой цвет, то тогда создать отдельную какую-нибудь переменную, где будут хранится все цвета. Например в css, где ты инициализируешь цвета через переменные. Но это гемор, проще как мне кажется, оставить цвет от ant design

2024-09-25 14:35 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> -                    <Form.Item key={field.name} name={field.name}>
Аналогично, от этого избавится.

2024-09-25 14:36 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +                    <Form.Item
Если посмотреть документацию от Ant Design, то Form.Item это context, который предоставляет например тому же Input все необходимые onChange, onBlur методы для корректной работы.

2024-09-25 14:37 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +                            onBlur={(e) =>
Выше пояснил, почему стоит его убрать

2024-09-25 14:37 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
>                          className="custom-button"
Перенести на модульные стили

2024-09-25 17:35 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +const userFields = [
Ты имеешь ввиду просто вставить это все HTML кодом?

Во первых, это шаблон, который через копи-паст может вставляться с одной страницы на другу, и не нужно разбираться что куда в верстке вставлять, а работать с данными. Не вижу смысла переделывать потому что там всего 2 инпута.

Во вторых, это сейчас 2 инпута. А может захотеться сделать больше. Что опять же будет проще добавить через данные, нежели разбираться в верстке

2024-09-25 17:57 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +        validate: [
Вот о чем я говорю https://github.com/caof19/yandex.game/blob/b8fa960fd67bf4c5e76db42b2cd184bdbdc08191/packages/client/src/pages/SignUp/index.tsx

2024-09-25 17:59 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +    const handleBlur = (fieldName: string, value: string, validateRule) => {
Как писал выше, потому что это шаблонное решение. Для него не подходит стандартный функционал Ant Design

2024-09-25 18:12 UTC, shuraleva requested changes

2024-09-25 18:12 UTC, shuraleva commented on packages/client/src/pages/SignIn/index.tsx
> +const userFields = [
> вставить это все HTML кодом?

Нет, у тебя же не будет больше HTML кода, а только компоненты Antd, никакой верстки. У Ильи все действительно выглядит по канону (на первый беглый взгляд)

2024-09-25 18:12 UTC, shuraleva commented on packages/client/src/pages/SignIn/index.tsx
> +        validate: [
Я все еще до конца не понимаю, почему rules хуже на твой взгляд. Это, вроде бы, покрывает все требования твои)

2024-09-25 18:17 UTC, ex1one commented on packages/client/src/service/user/Auth.ts
> +/*
Это вот комментарий к твоему закомментированному коду, получилось не очень понятно визуально)

2024-09-25 18:21 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> -                    <Form.Item key={field.name} name={field.name}>
Не совсем понял от чего избавится

2024-09-25 18:35 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +        validate: [
Пропс rules должен закрыть все твои желания) Уйдет кастомная обработка handleBlur и проверка полей в onFinish.

Но я все же настаиваю на использование jsx, без использования массива, в котором ты хранишь данные для inputs. Потому что у решения, которое ты написал, есть нюансы с которыми придется мирится либо опять же изменять логику и ее улучшать, чтобы избавится от дальнейших нюансов. 

Будущий кейс:
- Добавится какое-то условие динамичное в будущем на input? Которое будет зависеть от prop. Там придется придумывать новое решение, которое может опять же усложнить код. А у нас кейс - простой. Для простого кейса - сложное решение.

И это только 1 кейс, а их может быть еще несколько. Я топлю больше за то, чтобы ты убрал массив userFields, убрал кастомную реализацию обработки формы. Воспользовался rules. И перенес input в jsx.

Но если все же, хочется сохранить эту логику, то лучше чтобы ты вынес это в отдельный хук.

2024-09-25 18:40 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> -                    <Form.Item key={field.name} name={field.name}>
Я тут имел ввиду, чтобы ты не использовал userFields

2024-09-25 18:52 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +        validate: [
Да, по поводу кастомной валидации согласен, не знал что можно свои регулярки пихать с кастомным сообщением. Исправлю. так и правда удобнее

По поводу массива все равно не понимаю, как и не осознаю его сложность. Просто эту схему я часто где использую (как на беке, так и на фронте), возможно и правда не вижу недостатков. Можешь привести в пример кейс (более конкретный), где эта схема проиграет? 

Мои знания в React ну очень скудные, но если я верно тебя понял, то твой кейс сейчас можно решить просто повесив функцию на onChange

2024-09-25 19:31 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +import "./style.css";
Перенес на моудльные

2024-09-25 19:32 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +    const handleBlur = (fieldName: string, value: string, validateRule) => {
Убрал слушатель с инпутов

2024-09-25 19:32 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +                        help={errors[field.name]}
Убрал

2024-09-25 19:32 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +                            onBlur={(e) =>
Тоже убрал

2024-09-25 19:32 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
>                          className="custom-button"
Перенес

2024-09-26 19:35 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +const userFields = [
Избавился от массива

2024-09-26 19:35 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> +                        style: {
Убрал кастомный цвет

2024-09-26 19:35 UTC, caof19 commented on packages/client/src/pages/SignIn/index.tsx
> -                    <Form.Item key={field.name} name={field.name}>
Убрал

2024-09-29 13:34 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +const userFields = [
Массив можно теперь убрать. Не используется

2024-09-29 13:35 UTC, ex1one commented on packages/client/src/pages/SignIn/index.tsx
> +    const handleFinish = (val) => {
Это можно переписать на async/await. Но тоже пойдет)

2024-09-29 13:35 UTC, ex1one approved these changes

2024-10-01 11:14 UTC, kyzinatra commented on packages/client/src/pages/SignIn/index.tsx
> +                    duration: 3, // Время исчезновения через 3 секунды
Можно лучше: не стоит писать комментарии ради комментариев. Тут и так ясна суть этого кода, но нарушается Single Source of Truth

2024-10-01 11:14 UTC, kyzinatra commented on packages/client/src/pages/SignIn/index.tsx
> +
url стоит вынести в константу

2024-10-01 11:15 UTC, kyzinatra commented on packages/client/src/pages/SignIn/SignIn.module.css
> +    -moz-border-radius: 10px;
Бордер радиус достаточно поддерживается) Можно не указывать суффиксы

2024-10-01 11:16 UTC, kyzinatra approved these changes
Отличная работа! Отличная работа над версткой и api. Круто, что вы выводите ошибки. ВОпросов по работе у меня нет

2024-10-01 12:54 UTC, shuraleva approved these changes

2024-10-01 19:16 UTC, merged